import site from '~/data/site.config.yml';

const buildTime = import.meta.env.BUILD_TIME;
const buildTime_formattedDate = new Date(buildTime).toLocaleDateString('en-US', {
  year: 'numeric',
  month: 'long',
  day: 'numeric',
});

export async function GET() {
  const content = `
/* The humans responsible & colophon */
/* humanstxt.org */

 _ _   _ ___
/ | | | | _ \`
| | |_| |  _/
|_|.___/|_|


/* AUTHOR */
Name: ${site.author.name}
Email: ${site.author.email}
Github: 'https://github.com/'${site.author.social.github}
X: @${site.author.social.x}
Location: ${site.author.location}

/* THANKS */
Jekyll (https://jekyllrb.com/)

/* SITE */
Site Name: ${site.title}
Site URL: ${site.url}
Last update: ${buildTime_formattedDate}
Language: ${site.language.name}
Timezone: ${site.timezone}
Generated by: ${site.framework}
Hosted on: ${site.hosting}
  `;

  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
};
